###
POST http://localhost:8008/user/create
Content-Type: application/json
sessionid: 1111
cuid: system

{
  "name": "uouho",
  "birthdate": "1-1-2000",
  "email": "muster@gmail.de",
  "password": "password",
  "description": "Hi, I am a driver!"
}

###

POST http://localhost:8008/user/update/62b6ea097361e0637f39e05e
Content-Type: application/json
sessionid: 1111
cuid: system

{
  "name": "safsaökjiöds",
  "birthdate": "1-1-2000",
  "email": "muster@gmail.de",
  "password": "password",
  "vehicles": ["620cbeaecc90432d95b598a0"],
  "description": "Hi, I like driving!",
  "averageEvalOfRides": 4
}

###

GET http://localhost:8008/user/getAll
sessionid: 1111
cuid: system

###

GET http://localhost:8008/user/findById/62b4622328ed0b0006bdba40
sessionid: 1111
cuid: system

###

DELETE http://localhost:8008/user/delete/620cbeaecc90432d95b598a6
Content-Type: application/json
sessionid: 1111
cuid: system
